export default {
  LIST_AUTHORS: 'LIST_AUTHORS',
  GET_AUTHOR: 'GET_AUTHOR',
  CREATE_AUTHOR: 'CREATE_AUTHOR',
  UPDATE_AUTHOR: 'UPDATE_AUTHOR',
  DELETE_AUTHOR: 'DELETE_AUTHOR',
  LIST_BOOKS: 'LIST_BOOKS',
  GET_BOOK: 'GET_BOOK',
  CREATE_BOOK: 'CREATE_BOOK',
  UPDATE_BOOK: 'UPDATE_BOOK',
  DELETE_BOOK: 'DELETE_BOOK'
}
