version: '3'
services:
  server:
    build:
      context: .
      dockerfile: data/Dockerfile.server
    ports:
      - "8080:8080"
    volumes:
      - ./data/config.yml:/config.yml
    restart: always
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: data/Dockerfile.db
    ports:
      - "3306:3306" 
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookshelf
      MYSQL_USER: bookshelf
      MYSQL_PASSWORD: bookshelf
volumes:
    db_data:
      driver: local
